Repository jordanbrauer/unit-converter, pull requests merged in 2021-12, with the labels that each got.

#179 Run PHPUnit against 8.0, 8.1, fix 8.1 deprecation warnings, drop PHP 7.3
  .gitattributes
  .github/workflows/ci.yml
  .gitignore
  composer.json
  composer.lock
  phpunit.xml
  src/Support/Collection.php
Labels: enhancement

#180 fix: TypeError when converting units from one family to another (#177)
  src/Exception/BadUnit.php
  src/UnitConverter.php
  tests/unit/UnitConverter.spec.php
Labels: bug

#175 upgrade changelog dev package
  composer.json
  composer.lock
Labels: dependencies

#157 add cubic cm and cubic m
  src/Measure.php
  src/Unit/Volume/CubicCentimeter.php
  src/Unit/Volume/CubicMillimeter.php
Labels: enhancement
